version: '3'
services:
  couchdb:
    image: couchdb:latest
    container_name: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpassword
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - couchdb_network

volumes:
  couchdb_data:

networks:
  couchdb_network:
    driver: bridge
